kind: pipeline
type: kubernetes
name: build_and_push
platform:
  os: linux
  arch: arm64
steps:
- name: build
  image: repo-docker-hosted.angeloxx.lan/angeloxx/drone/plugins/galaxy:stable
  pull: always
  settings:
    key: 
      from_secret: API_TOKEN
    collection: rangeid/icinga
  when:
    branch:
    - master
    event:
    - push
    - custom
