namespace: rangeid
name: icinga
version: 0.0.3
readme: README.md

authors:
    - Angelo Conforti <angeloxx@angeloxx.it>

description: Implements Icinga API
license:
    - BSD-3-Clause

repository: "https://github.com/rangeid/ansible-icinga-collection"
issues: "https://github.com/rangeid/ansible-icinga-collection/issues"
documentation: "https://github.com/rangeid/ansible-icinga-collection/blob/master/README.md"

tags:
    - monitoring
    - icinga

dependencies:
    "community.general" : "*"

